---
- name: add tomcat admin user
  tamplate: 
     src: tamplates/mytomuser.j2
     dest: /opt/tomcat/conf/tomcat-users.xml  


- name: change context xml file
  tamplate: 
     src: tamplates/mytomcontext.j2
     dest: /opt/tomcat/webapps/manager/META-INF/context.xml  


- name: change host xml file
  tamplate: 
     src: tamplates/mytomhostcontext.j2
     dest: /opt/tomcat/webapps/host-manager/META-INF/context.xml  